DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS beverages;
DROP TABLE IF EXISTS cafes;

CREATE TABLE cafes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    location TEXT NOT NULL
);

CREATE TABLE reviews (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    cafeId INTEGER,
    author TEXT NOT NULL,
    rating FLOAT NOT NULL DEFAULT 0.0,
    description TEXT NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cafeId) REFERENCES cafes(id)
);

CREATE TABLE beverages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    cafeId INTEGER,
    name TEXT NOT NULL,
    recipe TEXT NOT NULL,
    price FLOAT NOT NULL DEFAULT 0.0,
    FOREIGN KEY (cafeId) REFERENCES cafes(id)
);